micronaut:
  application:
    name: communicationService
datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
netty:
  default:
    allocator:
      max-order: 3
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
liquibase:
  datasources:
    default:
      change-log: classpath:db/liquibase-changelog.xml
